#!/usr/bin/env zsh

# Load scripting additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Select previous window or if that fails the first window of the screen.
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"

# Focus zathura windows when they are created
yabai -m signal --add app="^zathura$" event=window_created action="~/.config/yabai/focus_last_window_id.zsh zathura"

# Global settings
yabai -m config top_padding 0

# Focus settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

# Spawning settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_origin_display        cursor

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# General space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
#
# Visual settings
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Create a couple of workspaces up to $YABAI_MAX_SPACES
YABAI_MAX_SPACES=5
for sp in {1..$YABAI_MAX_SPACES}; do
    yabai -m query --spaces --space $sp &> /dev/null || yabai -m space --create
done

# Tie applications to spaces
yabai -m rule --add app="^iTerm2$" space=^1
yabai -m rule --add app="^Telegram$" space=^2
yabai -m rule --add app="^DeaDBeeF$" space=^2
yabai -m rule --add app="^FireFox$" space=^3
yabai -m rule --add app="^Safari$" space=^3
yabai -m rule --add app="^Mattermost$" space=^5

# Enforce the number of spaces regardless of the number of displays
yabai -m signal --add event=display_added action="yabai -m space --destroy \$(yabai -m query --spaces --display 1 | jq '.[-1].index')"
yabai -m signal --add event=display_removed action="yabai -m space --create"
